### ISSUE TITLE
Dependencies containing underscores can't be resolved

### ISSUE THREAD

**Issue by paulmelnikow** [brunolange/artifax#7]
Hi Bruno!

We're continuing to use Artifax in our dependency graph (via [werkit](https://github.com/metabolize/werkit/)). We're running into an unexpected behavior where underscores in key names cause Artifax not to be able to find the dependency:

```py
afx = Artifax({"b": lambda a: a})
afx.set(a=123)
print(afx.build(targets=["b"]))
# prints 123

afx = Artifax({"b": lambda a_snake: a_snake})
afx.set(a_snake=123)
print(afx.build(targets=["b"]))
# raises UnresolvedDependencyError; expected 123

afx = Artifax({"b": lambda a_snake: a_snake})
afx.set(**{"a-snake": 123})
print(afx.build(targets=["b"]))
# prints 123

afx = Artifax({
  "a_snake": lambda a: a,
  "b": lambda a_snake: a_snake,
})
afx.set(a=123)
print(afx.build(targets=["b"]))
# raises UnresolvedDependencyError; expected 123
```

Not sure if there is something deliberate going on here? I'm guessing this is just a bug. Let me know if you'd like me to open a PR!

**Comment by brunolange** [comment]
Hi Paul,

There was some logic in place that tried to conciliate nodes that contained dash characters by replacing dashes with underscores so that those nodes could be directly referenced in function arguments.

I have now published version 0.4, wherein `Artifax` will no longer attempt to perform such replacements. Not only because of the bug you found but because I realize now this whole strategy is flawed in that the original reference to a node could be lost should any pair of nodes have the same name except for dashes and underscores (e.g 'a-snake' and 'a_snake').

This means that nodes defined as dictionary keys need to referenced in function arguments exactly as they're spelled. If that's not possible due to a node containing a special character such as "-", the `At` syntax can be employed to define the proper dependencies. You can find more info in the PR: https://github.com/brunolange/artifax/pull/8

```python
def bang(v):
    return f"{v}!"

afx = Artifax(
    cool=At("my-message", bang),
    **{
        "my-message": "hello world",
    }
)

print(afx.build(targets=["cool"]))  # prints "hello world!"
```

So please update to `artifax==0.4` and let me know if you run into any issues.

**Comment by paulmelnikow** [comment]
Thank you so much for addressing this! Sorry I missed your comment before. We'll take it for a spin and let you know. Since you merged my failing test, I imagine it will work just fine! 😁

**Comment by brunolange** [comment]
Hi Paul, I'm closing this issue but feel free to open a new one should you run into any new issues.
